version: '3'

services:    
  ntfy:
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=${TZ}
    image: binwiederhier/ntfy
    labels:
      - homepage.group=Monitoring
      - homepage.name=ntfy
      - homepage.icon=ntfy
      - homepage.href=${PROTOCOL}://ntfy.${HOSTNAME}
    user: ${UID}:${GID}
    restart: unless-stopped
    volumes:
      - ./ntfy/cache:/var/cache/ntfy
      - ./ntfy/etc:/etc/ntfy

  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    labels:
      - homepage.group=Monitoring
      - homepage.name=Uptime
      - homepage.icon=uptime-kuma
      - homepage.href=${PROTOCOL}://uptime.${HOSTNAME}
      - homepage.showStats=true
    restart: unless-stopped
    volumes:
      - ./uptime-kuma:/app/data

  watchtower:
    container_name: watchtower
    command:
      - "--http-api-token=${WATCHTOWER_API_KEY}"
      - "--http-api-metrics=true"
    image: containrrr/watchtower
    labels:
      - homepage.group=Monitoring
      - homepage.name=Watchtower
      - homepage.icon=watchtower
      - homepage.widget.type=watchtower
      - homepage.widget.url=http://watchtower:8080
      - homepage.widget.fields=["containers_scanned", "containers_updated", "containers_failed"]
      - homepage.widget.key=${WATCHTOWER_API_KEY}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: docker
