version: '3'

services:
  syncthing:
    container_name: syncthing
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    image: linuxserver/syncthing
    labels:
      - homepage.group=Productivity
      - homepage.name=Syncthing
      - homepage.icon=syncthing
      - homepage.href=${PROTOCOL}://syncthing.${HOSTNAME}
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    volumes:
      - ./syncthing:/config
      - ~/storage:/storage

  vaultwarden:
    container_name: vaultwarden
    environment:
      - TZ=${TZ}
    image: vaultwarden/server
    labels:
      - homepage.group=Productivity
      - homepage.name=Vaultwarden
      - homepage.icon=vaultwarden
      - homepage.href=${PROTOCOL}://vaultwarden.${HOSTNAME}
    restart: unless-stopped
    volumes:
      - ./vaultwarden:/data


networks:
  default:
    name: docker
